### ISSUE TITLE
No need to append image to the page

### ISSUE THREAD

**Issue by arnellebalane** [use-hooks/react-hooks-image-size#4]
Hi, perhaps it's not necessary to append the `img` element to the page in order for it to trigger the `load` event. I've tested it in [this fiddle](http://jsfiddle.net/w60nypa1/1/) and it works just fine.

The code that adds `display: none` to the `img` tag, as well as appends/removes it from the page can be removed to reduce the source's size. `document.createElement('img')` can also be replaced with `new Image()` since they're functionally the same.

What do you think? 😃

**Comment by int64ago** [comment]
Wow, thanks for this, it's my mistake, fixed be802af1405db52e972c9d0c92de80919db10717

**Comment by int64ago** [comment]
https://github.com/use-hooks/react-hooks-video-meta/commit/d7d028b56bcefc6e0e7d2fb1b5b19b6aa922beb4

fixed this, too :-)

**Comment by arnellebalane** [comment]
@int64ago It looks like it's still [setting the image's style to `display: none`](https://github.com/use-hooks/react-hooks-image-size/blob/master/src/index.js#L19), which is no longer needed since the image is no longer getting appended to the page anyway.

Great work on this hook btw 💯
